### ISSUE TITLE
Seg fault in in LogDialog::get_data(int, QStringList*) 

### ISSUE THREAD

**Issue by mikelma** [ladecadence/ASHAB-Telemetry#1]
#0  0x00005555555756bb in LogDialog::get_data(int, QStringList*) ()
#1  0x0000555555581324 in ChartsDialog::update_chart() ()
#2  0x00005555555845a1 in ChartsDialog::qt_metacall(QMetaObject::Call, int, void**) ()
#3  0x00007ffff6d07298 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/libQt5Core.so.5
#4  0x00007ffff79622c3 in QAbstractButton::toggled(bool) () from /usr/lib/libQt5Widgets.so.5
#5  0x00007ffff79626f3 in ?? () from /usr/lib/libQt5Widgets.so.5
#6  0x00007ffff7963d0b in QAbstractButton::setChecked(bool) () from /usr/lib/libQt5Widgets.so.5
#7  0x0000555555582252 in ChartsDialog::ChartsDialog(QWidget*, LogDialog*) ()
#8  0x0000555555569e18 in MainWindow::MainWindow(QWidget*) ()
#9  0x000055555556357d in main ()

**Comment by ladecadence** [comment]
Debería estar arreglado en [f13c76e](https://github.com/ladecadence/ASHAB-Telemetry/commit/f13c76e645a2469022602c98e1b3247f0a85460d), pullea y prueba.
